version: '3'

services:
  mysql-db:
    build:
      context: "./mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: mysql_serve
    ports:
      - "3306:3306"
    tty: true
    restart: always
    volumes:
      - "./_data:/var/lib/mysql"